### ISSUE TITLE
November 20 Release Punchlist

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#105]
- [x] Update repo Wiki - Install Guide, Tool Bar, & Style Guide (issue https://github.com/USEPA/EPA-Metadata-Editor-Pro/issues/7) 
- [x] Disable Esri Metadata Tools by default #92 
- [x] UI Refresh #87 
- [ ] Digitally Sign Addin #72
- [x] Bug With EPA Keyworsd #100 
- [x] Create Keywords to tags button #98 
- [ ] Additional validation message for epa req. elements #115

**Comment by jmaxmarno** [comment]
No time for UI Refresh or additional validation in this release
