### ISSUE TITLE
py toolbox cleanup fix TODOs

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#59]
Go back through the toolbox and address the TODOs:
- [x]  Check Upgrade Tool results and also look into disabling it depending on current md format (like the out of the box tool) continued in issue #77 
- [x]  blank.xml - Update the ArcGIS Profile to ISO19115-1
- [x]  Find method to merge the records. (see issue #74 )
- [x]  Review Sync options if a Feature class and include in pre-Export, post: Import, Upgrade, Clear, Merge (See issue #75 ) 
- [x]  Export to ISO in Pro now has several options... include in toolbox
- [x]  Go back thru tools and make batch-able where applicable
- [x]  Create method on Pro-Open that copies tools to US EPA Directory
- [x]  Update Tool buttons to call from US EPA Directory.

**Comment by dspinosa** [comment]
For the upgrade method, maybe check inside the code to see what format.

**Comment by dspinosa** [comment]
![image](https://user-images.githubusercontent.com/5093530/94295264-d28be100-ff15-11ea-8026-10e2c139a9c1.png)
