### ISSUE TITLE
Beta Testing Feedback

### ISSUE THREAD

**Issue by jmaxmarno** [USEPA/EPA-Metadata-Editor-Pro#86]
### EME Pro Beta Testing Feedback 2020

- [x] Refresh Pro UI on tool execution #87 
- [x] Upgrade Tool Malfunction #84 #77 #85 
- [x] Link from Catalog//Metadata to EME Tools #92
- [x] Not able to run tools on standalone xml #88 
- [x] Possible confusion with tool parameters Source vs. Target ?

**Comment by dspinosa** [comment]
Separate issues have been created
